### ISSUE TITLE
Pitchers' player pages should load pitches as default

### ISSUE THREAD

**Issue by albertlyu** [kruser/pitchfx-site#37]
If player's primary position is a pitcher, load pitches (rk-pitches div) as landing page instead of atbats (rk-at-bats div). 

entry.js would need to be refactored. I tested the following change to default the partial page to pitches:

```
    }).otherwise({
        redirectTo : '/pitches'
    });
```

We would need to somehow persist the playerInfo array or just the playerInfo.primary_position_txt variable itself in order to change the redirectTo parameter based on an if statement.

**Comment by kruser** [comment]
This is a good idea. Here's how I'd solve it....
1. go to the player.html EJS template. Where we have....

``` html
<body ng-app="pitchfx">
```

Change it to...

``` html
<body ng-app="pitchfx" data-default-route="/atbats">
```

Except instead of hard coding /atbats you'll want to write some <%= playerInfo.primary_position %> EJS template code to selectively write either /atbats or /pitches based on the player's primary position.

Then you can read the body's data-default-route attribute in the entry.js, setup a variable above where the config is created, and reference that variable in the config setup. That' entry.js is where I setup the entire AngularJS app, so you can just read the data-default-route attribute with plain old javascript, something like document.body.attributes.dataDefaultRoute.
