### ISSUE TITLE
MLB C&D Discussion

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#50]
MLBAM sent a cease and desist letter today for PitchFX.org. I'm putting it up here for discussion.
https://drive.google.com/file/d/0B9ERgAQ83pATZ1dObTY0c1kxb0JFZGhPS2NWT0I2REstaUJn/edit?usp=sharing

**Comment by kruser** [comment]
The gist of the letter...
- stop using the player images
- stop using the PitchFX.org domain name

**Comment by albertlyu** [comment]
Well, we know there is precedence for removal of the player images. I think we should cooperate on that front. At least one other PITCHf/x site also had player images requested to be taken down in a C&D letter.

As far as Pitchfx.org... they don't have an issue with calling it a PITCHf/x tool (like other sites). It's just the domain name. This is disappointing to me, because I always thought PITCHf/x was a Sportvision term, and not a trademark owned by MLBAM.

I don't know much about trademark infringement. I'd lean towards cooperating. Though it'd be good if you could talk to them on the phone about it to get a good idea of what exactly they'd want to bring the site into compliance. We can think of a new site name (and that's really up to you, since it's your site). Though we can at least keep the Github project name.

**Comment by kruser** [comment]
I spoke with Sandra today who was very nice and understanding.

Here is what we need to do to get off of the MLBAM radar.
- No team logos
  - remove background images on the player cards
  - scrub the logos from the caps - but we can still use the player mug shots
- PitchFX is a trademark by Sportsvision, and enforced by a partnership with MLBAM. So I'm sad to say we need a new domain name. Suggestions welcome.

MLBAM says use of the data is ok for now as long as the site is not commercial.

**Comment by albertlyu** [comment]
Sounds good. Glad that we can keep the player mug shots. That's actually a great feature. But I wonder what the best way to remove the logos from the caps is...

As far as new domain names, as long as the domain name doesn't contain pitchfx, that's okay right? For example, pitchfx.texasleaguers.com

**Comment by kruser** [comment]
For the mugs, I'll position another generic logo, probably a baseball, on top of the hats using CSS.

They don't want PitchFX in the domain name, I take that as sub-domain too. Regardless, I have no interest in using a subdomain.

**Comment by kruser** [comment]
My favorite domain name generator: http://impossibility.org/

**Comment by albertlyu** [comment]
Keywords to search for: pitch, pitcher, pitching, scouting, scout. Maybe you can use 'Scout Assist' and make that the brand? scoutassist.com is for sale at $995 though.

**Comment by kruser** [comment]
Closing this discussion as we have actionable items now.
