### ISSUE TITLE
Group the different pitch heatmaps

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#63]
We have a nice list of heatmaps now, but the list is getting a little too long.

This task is to create a grouping mechanism for each one.
- Sabermetric Outcomes
  - wOBA/BIP
  - BABIP
  - BIP
- Plate Discipline
  - Swing Rate
  - Whiff Rate
  - Whiffs/Swing
  - Called Strike Rate
- Batted Ball Results
  - Grounders/BIP
  - Linedrives/BIP
  - Flyballs/BIP
  - Popups/BIP

![image](https://cloud.githubusercontent.com/assets/2208700/2673796/8a7444f6-c0f7-11e3-974f-3bada38098dd.png)

**Comment by kruser** [comment]
This accordion directive is already at our disposal since we bundle ui-bootstrap.

http://angular-ui.github.io/bootstrap/#/accordion

I'll arrange the charts into this structure and leave the simple select on mobile.

**Comment by kruser** [comment]
I put the groups in.

Developers - you'll need to run a `bower update` from the app folder on your next code update.

**Comment by albertlyu** [comment]
This is great. I really like this fix. Opens the door for better organization of even more heatmaps in the future.

I may submit another issue with even more heatmaps with updated and/or additional groupings. For example, I like Contact Rate, Contact / Swing, etc., i.e. Brett Gardner vs. Mark Reynolds.

**Comment by kruser** [comment]
Sounds good @albertlyu. Just put a new "group" property on the definition on the chart and a new accordion group will be created.

**Comment by albertlyu** [comment]
Note that I am working on more heatmaps and a bit of reorganization. I will submit a pull request soon, but I will list the updated heatmap groups here. Feel free to validate this with your thoughts:

Pitch Results
- Swing Rate
- Whiff Rate
- Called Strike Rate
- Foul Rate
- Ball In Play Rate

Swing Results
- Whiffs/Swing
- Contact Rate
- Contact/Swing
- Fouls/Swing
- BIP/Swing

Batted Ball Results
- Grounders/BIP
- Linedrives/BIP
- Flyballs/BIP
- Popouts/BIP

Sabermetric Results
- wOBA/BIP
- BABIP

The idea is that Pitch Results all have denominator 'pitches,' whereas Swing Results all have denominator 'swings.' Well, except Contact Rate, which I only added to Swing Results since we don't want more than 5 heatmaps per accordion group.
