### ISSUE TITLE
Highcharts heatmaps

### ISSUE THREAD

**Issue by albertlyu** [kruser/pitchfx-site#73]
I thought this would have been fixed by Highcharts by now after their major Highcharts 4.0 release. But our heatmaps are still down.

![image](https://cloud.githubusercontent.com/assets/1390356/2778035/5f541544-caed-11e3-8889-3da1b01b673e.png)

The updated demo on their site has been fixed though, as you see here:
http://www.highcharts.com/demo/heatmap/

**Comment by kruser** [comment]
This makes me nervous about just pulling in the latest highcharts. We'll eventually want to bower install these dependencies too so that we can stay on a specified version until we're ready to upgrade. I expect highmaps is now in bower. At the time I put in those initial heatmaps it wasn't.

Good catch Albert. The site has been updated.

**Comment by albertlyu** [comment]
It looks to me that the heatmaps modules have been moved from highmaps to highcharts, which would explain why the path for the heatmap.js changed. If you see Highcharts' site, the demos for the heatmaps are now under highcharts (where as before, they weren't under highcharts, but were presumably under highmaps http://web.archive.org/web/20131229232006/http://www.highcharts.com/demo/).

If that's the case, you should be able to bower install highcharts now that it's being apparently supported, without need of the beta version of highmaps dependency.

**Comment by kruser** [comment]
Not sure about these default pastel colors either ;). I'll open a separate issue to pick a template for these things.
